# version: '3.8' (mantenha o seu)

services:
  github-runner:
    build: .
    env_file: .env
    environment:
      - GITHUB_OWNER=${GITHUB_OWNER}
      - GITHUB_REPOSITORY=${GITHUB_REPO}
      - GITHUB_PAT=${GITHUB_PAT}
      - RUNNER_TOKEN=${RUNNER_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Mapeia uma pasta local chamada 'runner-work' para o diretório de trabalho do runner
      - ./runner-work:/home/runner/_work
    restart: unless-stopped
    privileged: true
    stdin_open: true
    tty: true

# Remova completamente esta seção de 'volumes' no final do arquivo
# volumes:
#  runner-work: