version: '3.8'

services:
  github-runner:
    build: .
    # Esta linha garante que as variáveis do arquivo .env sejam carregadas
    env_file: .env
    environment:
      # As variáveis carregadas pelo env_file são passadas para o container aqui
      - GITHUB_OWNER=${GITHUB_OWNER}
      - GITHUB_REPOSITORY=${GITHUB_REPO}
      - GITHUB_PAT=${GITHUB_PAT}
      - RUNNER_TOKEN=${RUNNER_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-work:/home/runner/_work
    restart: unless-stopped
    # Privileged é útil para cenários de Docker-in-Docker, pode manter.
    privileged: true

volumes:
  runner-work: