version: '3.8'

services:
  github-runner:
    build: .
    env_file: .env
    environment:
      - GITHUB_OWNER=${GITHUB_OWNER}
      - GITHUB_REPOSITORY=${GITHUB_REPO}
      - GITHUB_PAT=${GITHUB_PAT}
      - RUNNER_TOKEN=${RUNNER_TOKEN}
    volumes:
      # Permite que o runner chame o Docker do servidor
      - /var/run/docker.sock:/var/run/docker.sock
      # CRÍTICO: Mapeia uma pasta do servidor para a pasta de trabalho do runner
      - ./runner-work:/home/runner/_work
    restart: unless-stopped
    privileged: true
    stdin_open: true
    tty: true

# NÂO deve haver uma seção 'volumes:' aqui no final