name: Runner test

on:
  workflow_dispatch:

jobs:
  Runner_test:
    runs-on: self-hosted

    steps:
      - name: test
        run: |
          echo "testado"
          nslookup 192.168.68.114
      - name: Minio Deploy
        uses: Matheus-Thurler/reusable-actions/minio-cli/action.yaml@master
        with:
          endpoint: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: 'mybucket'
          source_dir 'public'
          target_dir: '/'